services:
  cdr-app:
    container_name: cdr-app
    build:
      context: ./cdr-generator-app
    ports:
      - "8080:8080"
    environment:
      CDR_DATABASE_URL: ${CDR_DATABASE_URL}
      CDR_DATABASE_USERNAME: ${CDR_DATABASE_USERNAME}
      CDR_DATABASE_PASSWORD: ${CDR_DATABASE_PASSWORD}
