server:
  port: 8081

spring:
  application:
    name: brt-app

  profiles.include: db,rabbitmq

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
