spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${CDR_DATABASE_URL}
    username: ${CDR_DATABASE_USERNAME}
    password: ${CDR_DATABASE_PASSWORD}
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.yaml

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

