spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

rabbitmq:
  queue-name: ${RABBIT_MQ_QUEUE_NAME}
  exchange-name: ${RABBIT_MQ_EXCHANGE_NAME}
  routing-key: ${RABBIT_MQ_ROUTING_KEY}